package com.softkit.vo;

public enum Step {
    START,
    CANDIDATE,
    SPECIALISATIONS,
    TECHNOLOGIES,
    EXPERIENCE,
    ENGLISH_LEVEL,
    CITY_OR_LOCATION,
    EMPLOYMENT,
    MIN_SALARY,
    MAX_SALARY,
    DONE_BASIC_REGISTRATION,
    PHONE,
    AGE,
    SUMMARY,
    DONE_REGISTRATION
}
